# Generated by Django 3.2.5 on 2023-05-18 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='writer',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='writer',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='Follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writer',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='Following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writer',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writer',
            name='verification_code',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='writer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
