# Generated by Django 3.2.5 on 2023-05-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_auto_20230518_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='is_email_verified',
        ),
    ]
