# Generated by Django 3.2.5 on 2023-05-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0003_remove_writer_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
