# Generated by Django 3.2.5 on 2023-05-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0005_auto_20230519_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='writer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
