# Generated by Django 3.2.5 on 2023-05-19 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0006_auto_20230519_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='Follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writer',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='Following', to=settings.AUTH_USER_MODEL),
        ),
    ]
