# Generated by Django 3.2.5 on 2023-05-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0007_auto_20230519_0021'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='writer',
            managers=[
            ],
        ),
    ]
