# Generated by Django 4.2.5 on 2023-10-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_mock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mastery_fields',
        ),
    ]
