# Generated by Django 4.2.5 on 2023-10-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='success_metrics',
            new_name='success_matrics',
        ),
    ]
