# Generated by Django 4.2.5 on 2023-10-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_rename_success_metrics_onboarding_success_matrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='partners',
        ),
    ]
