# Generated by Django 4.2.5 on 2023-10-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_remove_onboarding_partners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='board_id',
            new_name='board',
        ),
    ]
