# Generated by Django 4.2.6 on 2023-10-23 19:50

import django.contrib.postgres.fields
from django.db import migrations, models
import onboarding.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_remove_onboarding_reward_onboarding_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='rewards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=onboarding.models.default_array, size=None),
        ),
    ]
